# Generated by Django 2.2.8 on 2020-05-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(default=0)),
                ('registor_index', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя:')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия:')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество:')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('graduated', models.CharField(max_length=150, verbose_name='Наименование учебного заведения:')),
                ('near', models.CharField(max_length=70, verbose_name='Город, Район')),
                ('certificate_status', models.CharField(default='Свидетельство', max_length=25, verbose_name='и получил(а): ')),
                ('certificate_number', models.CharField(max_length=50, verbose_name='Серия и номер (свидетельство, аттестат или диплом)')),
                ('certificate_date', models.IntegerField(verbose_name='Год выдачи (свидетельство, аттестат или диплом)')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('nationality', models.CharField(max_length=50, verbose_name='Национальность')),
                ('passport_or_certificate', models.CharField(max_length=70, verbose_name='Номер паспорта или свидетельство')),
                ('floor', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женшина', 'Женшина')], default='Мужчина', max_length=10, verbose_name='Пол')),
                ('form_training', models.CharField(default='Очный', max_length=5, verbose_name='Форма обучение')),
                ('budget_contract', models.CharField(default='Контракт', max_length=10, verbose_name='Бюджет контракт')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальност')),
                ('father', models.CharField(max_length=100, verbose_name='Отец')),
                ('father_phone', models.IntegerField(verbose_name='Номер телефона')),
                ('mother', models.CharField(max_length=100, verbose_name='Мать')),
                ('mother_phone', models.IntegerField(verbose_name='Номер телефона')),
                ('place_of_residence', models.CharField(max_length=150, verbose_name='Место жителство студента')),
                ('phone_student', models.IntegerField(verbose_name='Номер телефона студента')),
                ('image_student', models.ImageField(upload_to='Student_Photo/', verbose_name='Фото студента')),
                ('image_passport_or_certificate', models.ImageField(upload_to='Statements/', verbose_name='Фото паспорта или свидетельсто о рд.')),
                ('image_certificate', models.ImageField(blank=True, null=True, upload_to='certificate/', verbose_name='Фото (свидетельство, аттестат или диплом).')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('Принят', 'Принят'), ('Не принят', 'Не принят')], default='В ожидании', max_length=10, verbose_name='Статус')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.CharField(default='В ожидании', max_length=100, verbose_name='Ответственный')),
                ('created_the_accepted', models.DateTimeField(auto_now_add=True)),
                ('image_certificate_priom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сертификат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявление',
                'ordering': ('-reg_number',),
            },
        ),
    ]
