# Generated by Django 2.2.8 on 2020-05-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='statement',
            name='father_phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
