# Generated by Django 2.2.8 on 2020-05-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_auto_20200511_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='mother_phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
